name: "update-meta-schemas"
on: workflow_dispatch

jobs:
  updateMetaSchemas:
    env:
      META_SCHEMAS_DIR: 'metaSchemas'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        id: extractBranch
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Update meta-schemas from schemasafe repo
        run: npm run updateMetaSchemas

      - name: Check metaSchema dir changes
        id: metaSchemaDirGitStatus
        run: echo "changes=$(git status ${{ env.PACKED_JS_PATH }} --porcelain)" >> $GITHUB_OUTPUT

      - name: Commit metaSchema dir changes
        id: commitMetaSchemaDirFiles
        if: steps.metaSchemaDirGitStatus.outputs.changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A ${{ env.META_SCHEMAS_DIR }}
          git commit -m "Update built-in meta-schemas"
          
      - name: Push metaSchema dir changes
        if: steps.commitMetaSchemaDirFiles.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
          force: true
          branch: ${{ steps.extractBranch.outputs.branch }}